# Variables Definition File

# Name of website:
site_title: Lizzy Website

# Title of page, appears e.g. in browser's tab:
page_title: $page_name / {{site_title}}

# E-mail address of webmaster, appears e.g. when Lizzy tries to point to futher help:
webmaster_email: webmaster@domain.net
webmaster_link: "<a href='mailto:{{webmaster_email}}'>Webmaster</a>"

lzy-sign-up further info:
    de: "<p>Für weitere Informationen kontaktieren Sie bitte den {{webmaster_link}}.</p><p><br />(Mit der Taste ESC dieses Overlay schliessen)</p>"
    _:  "<p>For further information contact the {{webmaster_link}}.</p><p><br />(Press ESC to remove overlay)</p>"

Main Menu:
    de: Hauptmenü
    _:  Main Menu

Navigation:
    de:

Skip to Main:
    de: Direkt zum Inhalt
    _:  Skip to Main

Skip to Navigation:
    de: Direkt zum Navigationsmenü
    _:  Skip to Navigation

Skip to Sitemap:
    de: Direkt zur Sitemap
    _:  Skip to Sitemap



## -> un-comment and adapt if needed:
#small-screen-footer:
#    _: '<span style="display: inline-block;">Small Screen Footer</span>'

#large-screen-footer:
#    _: '<span style="display: inline-block;">Large Screen Footer</span>'


__END__

Explanations:

# Simple Replacements:
    
key: value

# Variables with language variants:
key:
    de: german text
    en: english text
    _: default text - used when requested language resource is not available 


# Note: values for default language and supported languages are defined in config/config.yaml
