# Macro Enroll()
'Enroll me': 
    de: 'Hier eintragen'
    en: 'Sign up here'
    
'Enroll now': 
    de: 'Jetzt eintragen'
    en: Sign up now

'Enroll delete': 
    de: 'Eintrag löschen:'
    en: Delete entry

'Enroll delete now': 
    de: 'Eintrag löschen'
    en: Delete entry

'enroll entry already exists': 
    de: 'Dieser Name ist bereits eingetragen'
    en: This name has been entered before

'enroll name required': 
    de: 'Geben Sie Ihren'
    en: Enter your

'illegal email address': 
    de: 'Ungültige E-Mail Adresse'
    en: Invalid e-mail address

'enroll email wrong': 
    de: 'E-Mail Adresse stimmt nicht überein'
    en: Wrong e-mail address

'enroll entry too old': 
    de: 'Eintrag kann nur in den ersten 24 Stunden gelöscht werden'
    en: An entry can only be deleted within the first 24 hours

'no enroll entry found': 
    de: 'Kein passender Eintrag vorhanden'
    en: No entry found that fits

'Enroll add': 
    de: 'Eintragen:'
    en: 'Make new entry:'

'Enroll add comment': 
    de: '<p><strong>Bemerkung</strong>:</p><p>Sie können Ihren Eintrag innerhalb der nächsten 24h noch selbstständig löschen. </p><p>Dazu benötigen Sie die hier eingegebene E-Mail Adresse.</p>'
    en: '<p><strong>Comment</strong>:</p><p>You can delete this entry within the next 24 houtd.</p><p>To do so, you need to enter your e-mail address again which you just provided.</p>'

'Enroll delete comment': 
    de: '<p><strong>Bemerkung</strong>:</p><p>Wollen Sie diesen Eintrag löschen?<br />Dazu müssen Sie die E-Mail Adresse eingeben, mit der der Eintrag ursprünglich eingegeben wurde.</p>'
    en: '<p><strong>Comment</strong>:</p><p>Do you want to delete this entry?<br />To do so you need to enter your e-mail address which you provided before. </p>'

'Enroll delete too late comment': 
    de: '<p>Es ist zu viel Zeit verstrichen, um Ihren Eintrag selbstständig zu löschen.</p><p>Sie können sich für eine Änderung direkt an uns wenden.</p>'
    en: "<p>Too much time past since you made this entry, therefore you can no longer delete it on your own.</p><p>Please contact us, so we can make that modification for you.</p>"

'Enroll delete for': 
    de: 'Name'
    en: Name

placeholder name:
    de: Vorname Name
    en: First-name last-name

placeholder mobile number:
    de: Handynummer (optional)
    en: Mobile number (optional)